version: "3.8"

services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - QR_SECRET=your-qr-signing-secret-change-this
      - QR_TOKEN_EXPIRY=300
      - PUBLIC_BACKEND_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:5173
      - COOKIE_SECURE=false
      - COOKIE_SAME_SITE=lax
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # PostgreSQL Database (Optional - for production)
  # Uncomment to use PostgreSQL instead of SQLite
  # db:
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=attendance
  #     - POSTGRES_PASSWORD=attendance123
  #     - POSTGRES_DB=attendance_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
